export const KENYA_PARKS = [
    "Aberdare National Park",
    "Amboseli National Park",
    "Arabuko Sokoke National Park",
    "Central Island National Park",
    "Chyulu Hills National Park",
    "Hell's Gate National Park",
    "Kisite-Mpunguti Marine National Park",
    "Kiunga Marine National Reserve",
    "Kora National Park",
    "Lake Nakuru National Park",
    "Malindi Marine National Park",
    "Malka Mari National Park",
    "Meru National Park",
    "Mombasa Marine National Park",
    "Mount Elgon National Park",
    "Mount Kenya National Park",
    "Nairobi National Park",
    "Ndere Island National Park",
    "Ruma National Park",
    "Saiwa Swamp National Park",
    "Sibiloi National Park",
    "Tsavo East National Park",
    "Tsavo West National Park",
    "Watamu Marine National Park",
    "Kakamega Forest National Reserve",
    "Rimoi National Reserve",
    "Shimba Hills National Reserve",
    "Tana River Primate Reserve",
    "Arawale National Reserve",
    "Bisanadi National Reserve",
    "Boni National Reserve",
    "Buffalo Springs National Reserve",
    "Dodori National Reserve",
    "Kakuma National Reserve",
    "Kamnarok National Reserve",
    "Kiptagich National Reserve",
    "Laikipia National Reserve",
    "Losai National Reserve",
    "Maasai Mara National Reserve",
    "Mwea National Reserve",
    "Nasalot National Reserve",
    "Ndoto Mountains National Reserve",
    "Samburu National Reserve",
    "Shaba National Reserve",
    "South Kitui National Reserve",
    "South Turkana National Reserve",
    "Ol Pejeta Conservancy",
    "Taita Hills Wildlife Sanctuary"
];
